# Which is equivalent to
format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$helm\
$julia\
$python\
$terraform\
$memory_usage\
$gcloud\
$kubernetes\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$character"""

[gcloud]
format = "☁️  [$project]($style) "
style = "bright-blue"

[kubernetes]
format = '[☸️  $context-$namespace]($style) '
disabled = false
style = "dimmed white"

[python]
symbol = "🐍 "
format = "[${symbol}($virtualenv)]($style) "
style = "green"

[git_branch]
symbol = "🌱 "

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"
